{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.55b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asgi-{{ version }}.tar.gz
  sha256: 807e3a1c4cbccb70b99ebf06ed6fe2ac4ec0a45a803c3051d01ed984c7ff5212

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - asgiref ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.55b0
    - opentelemetry-semantic-conventions ==0.55b0
    - opentelemetry-util-http ==0.55b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation.asgi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-semantic-convention
    - conda-forge/opentelemetry-util-http
