{% set name = "opentelemetry-instrumentation-asgi" %}
{% set version = "0.45b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_asgi-{{ version }}.tar.gz
  sha256: 97f55620f163fd3d20323e9fd8dc3aacc826c03397213ff36b877e0f4b6b08a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - asgiref ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.45b0
    - opentelemetry-semantic-conventions ==0.45b0
    - opentelemetry-util-http ==0.45b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-asgi 
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-asgi 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asgi
  summary: ASGI instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
